#! ansible-playbook

- name: install dependencies
  hosts: k3s
  tags: kube_common
  roles:
    - kube-common

- name: Install OpenEBS ZFS LocalPV provisioner for persistent volume claims
  hosts: zfs_storage
  tags: zfs
  vars:
    storage_classes:
      - name: zfs-snap
        snapshots: "true"
        filesystem: zfs
        default: "true"
        poolname: "{{data_zpool}}/openebs/snap/fs"
      - name: zfs-nosnap
        snapshots: "false"
        filesystem: zfs
        poolname: "{{data_zpool}}/openebs/nosnap/fs"
      - name: zvol-snap
        snapshots: "true"
        filesystem: ext4
        poolname: "{{data_zpool}}/openebs/snap/vol"
      - name: zvol-nosnap
        snapshots: "false"
        filesystem: ext4
        poolname: "{{data_zpool}}/openebs/nosnap/vol"
  roles:
    - kube-zfs


- name: Setup Ingress (with LetsEncrypt certs and Cloudflare Tunnel)
  hosts: k3s
  tags: ingress
  vars_prompt:
    - name: cf_api_token
      private: true
      prompt: Cloudflare API token (leave empty to skip)
  roles:
    - kube-ingress
    - kube-acme
    - kube-cf-tunnel
  