- hosts: k3s
  tags: deps
  tasks:
    - pip:
        name: kubernetes

- hosts: zfs_storage
  tags: zfs
  tasks:
    - community.general.zfs:
        name: "{{data_zpool}}/{{item.name}}"
        state: present
        extra_zfs_properties: "{{item.props}}"
      with_items:
        - name: "csi/pv_snap"
          props:
            "com.sun:auto-snapshot": "true"
        - name: "csi/pv_no_snap"
          props:
            "com.sun:auto-snapshot": "false"
      become: true
    - kubernetes.core.k8s:
        kubeconfig: /etc/rancher/k3s/k3s.yaml
        namespace: default
        definition:
          apiVersion: v1
          kind: Pod
          metadata:
            name: nginx
          spec:
            containers:
              - name: nginx
                image: nginx:1.14.2
                ports:
                  - containerPort: 80
