- kubernetes.core.helm_repository:
    name: jetstack
    repo_url: https://charts.jetstack.io
- kubernetes.core.helm:
    name: cert-manager
    chart_ref: jetstack/cert-manager
    release_namespace: cert-manager
    kubeconfig: /etc/rancher/k3s/k3s.yaml
    create_namespace: true
    values:
      installCRDs: true
- name: Create Cloudflare API token secret
  when: cf_api_token
  kubernetes.core.k8s:
    kubeconfig: /etc/rancher/k3s/k3s.yaml
    definition:
      apiVersion: v1
      kind: Secret
      metadata:
        name: cloudflare-api-token-secret
        namespace: cert-manager
      type: Opaque
      stringData:
        api-token: "{{cf_api_token}}"
- name: Create certificate issuer
  kubernetes.core.k8s:
    kubeconfig: /etc/rancher/k3s/k3s.yaml
    definition:
      apiVersion: cert-manager.io/v1
      kind: ClusterIssuer
      metadata:
        name: cf-acme-issuer
        namespace: cert-manager
      spec:
        acme:
          server: https://acme-v02.api.letsencrypt.org/directory
          email: me@jamestali.com
          privateKeySecretRef:
            name: acme-account-key
          solvers:
            - dns01:
                cloudflare:
                  apiTokenSecretRef:
                    name: cloudflare-api-token-secret
                    key: api-token